command: ["uvicorn", "agent_server.start_server:app", "--host", "0.0.0.0", "--port", "$DATABRICKS_APP_PORT"]

env:
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  - name: MLFLOW_REGISTRY_URI
    value: "databricks-uc"
  - name: NEO4J_MAX_ROWS
    value: "25"
  - name: DATABRICKS_AGENT_MODEL
    valueFrom: "llm"
  - name: MLFLOW_EXPERIMENT_ID
    valueFrom: "experiment"
  - name: NEO4J_URI
    valueFrom: "neo4j_uri"
  - name: NEO4J_USERNAME
    valueFrom: "neo4j_username"
  - name: NEO4J_PASSWORD
    valueFrom: "neo4j_password"
  - name: NEO4J_DATABASE
    valueFrom: "neo4j_database"
