command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "$DATABRICKS_APP_PORT"]

env:
  - name: NEO4J_URI
    valueFrom: "neo4j_uri"
  - name: NEO4J_USERNAME
    valueFrom: "neo4j_username"
  - name: NEO4J_PASSWORD
    valueFrom: "neo4j_password"
  - name: NEO4J_DATABASE
    valueFrom: "neo4j_database"
  - name: NEO4J_MAX_ROWS
    value: "50"
